Ispit.Books/Models/Author.cs
using System.ComponentModel.DataAnnotations;

namespace Ispit.Books.Models
{
    public class Author
    {

        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        public string Name { get; set; }

        [StringLength(5000)]
        public string? Bio { get; set; }

    }
}

Ispit.Books/Models/Book.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ispit.Books.Models
{
    public class Book
    {

        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        public string Title { get; set; }

        [StringLength(4000)]
        public string? Description { get; set; }

        [Required]
        [StringLength(50)]
        public string Genre { get; set; }

        [ForeignKey("AuthorId")]
        public Author Author { get; set; }
        public int AuthorId { get; set; }

        [ForeignKey("PublisherId")]
        public Publisher Publisher { get; set; }
        public int PublisherId { get; set; }

        [ForeignKey("UserId")]
        public IdentityUser? User { get; set; }
        public string? UserId { get; set; }

    }
}

Ispit.Books/Models/ErrorViewModel.cs
namespace Ispit.Books.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Ispit.Books/Models/Publisher.cs
using System.ComponentModel.DataAnnotations;

namespace Ispit.Books.Models
{
    public class Publisher
    {

        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(150)]
        public string Name { get; set; }

    }
}

Ispit.Books/Controllers/BookAdminController.cs
using Ispit.Books.Data;
using Ispit.Books.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Ispit.Books.Controllers
{
    [Authorize]
    public class BookAdminController : Controller
    {

        private readonly ApplicationDbContext _context;
        private UserManager<IdentityUser> _userManager;

        public BookAdminController(ApplicationDbContext context, UserManager<IdentityUser> user)
        {
            _context = context;
            _userManager = user;
        }


        // GET: BookAdminController
        public async Task<ActionResult> Index()
        {
            var books = new List<Book>();
            if (await _userManager.IsInRoleAsync(_userManager.GetUserAsync(User).Result, "admin"))
            {
                books = _context.Books.Include("Author").Include("Publisher").ToList();
            }
            else
            {
                var user_id = _userManager.GetUserId(User);
                books = _context.Books.Include("Author").Include("Publisher").Where(b => b.UserId == user_id).ToList();
            }
           
            return View(books);
        }

        // GET: BookAdminController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: BookAdminController/Create
        public ActionResult Create()
        {
            ViewBag.UserId = _userManager.GetUserId(User);
            return View();
        }

        // POST: BookAdminController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Book new_book)
        {
            try
            {
                _context.Books.Add(new_book);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BookAdminController/Edit/5
        public ActionResult Edit(int id)
        {
            Book find_book = _context.Books.FirstOrDefault(b => b.Id == id);

            ViewBag.UserId = _userManager.GetUserId(User);

            ViewBag.Authors = _context.Authors.ToList();

            ViewBag.Publishers = _context.Publishers.ToList();

            return View(find_book);
        }

        // POST: BookAdminController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Book book)
        {
            try
            {
                _context.Books.Update(book);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BookAdminController/Delete/5
        public ActionResult Delete(int id)
        {
            if(id == 0)
            {
                return RedirectToAction("Index");
            }

            var book = _context.Books.Include("Author").Include("Publisher").SingleOrDefault(b => b.Id == id);

            if(book == null)
            {
                return RedirectToAction("Index");
            }

            return View(book);
        }

        // POST: BookAdminController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int id)
        {
            if(id == 0)
            {
                return RedirectToAction("Index");
            }

            try
            {
                var find_book = _context.Books.SingleOrDefault(b => b.Id == id);

                if(find_book == null)
                {
                    return RedirectToAction("Delete");
                }

                _context.Books.Remove(find_book);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Ispit.Books/Controllers/HomeController.cs
using Ispit.Books.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Ispit.Books.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Ispit.Books/Views/BookAdmin/Create.cshtml
@model Ispit.Books.Models.Book
@inject Ispit.Books.Data.ApplicationDbContext application_db_context

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <input type="hidden" name="UserId" value=@ViewBag.UserId />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Author</label>
                <select class="form-select" name="AuthorId" id="author_id">
                    <option selected>Select author</option>
                    @foreach (var author in application_db_context.Authors)
                    {
                        <option value="@author.Id">@author.Name.ToString()</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label class="control-label">Publisher</label>
                <select class="form-select" name="PublisherId" id="publisher_id">
                    <option selected>Select publisher</option>
                    @foreach (var publisher in application_db_context.Publishers)
                    {
                        <option value="@publisher.Id">@publisher.Name.ToString()</option>
                    }
                </select>
            </div>

            <br />

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Ispit.Books/Views/BookAdmin/Delete.cshtml
@model Ispit.Books.Models.Book

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Publisher.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Ispit.Books/Views/BookAdmin/Edit.cshtml
@model Ispit.Books.Models.Book



@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <input type="hidden" name="UserId" value=@ViewBag.UserId />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Author</label>
                <select class="form-select" name="AuthorId" id="author_id">
                    <option selected>Select author</option>
                    @foreach (var author in ViewBag.Authors)
                    {
                        if(author.Id == Model.AuthorId)
                        {
                            <option selected value="@author.Id">@author.Name.ToString()</option>
                        }
                        else
                        {
                            <option value="@author.Id">@author.Name.ToString()</option>
                        }

                    }
                </select>
            </div>
            <div class="form-group">
                <label class="control-label">Publisher</label>
                <select class="form-select" name="PublisherId" id="publisher_id">
                    <option selected>Select publisher</option>
                    @foreach (var publisher in ViewBag.Publishers)
                    {
                        @if(publisher.Id == Model.PublisherId)
                        {
                            <option selected value="@publisher.Id">@publisher.Name.ToString()</option>
                        }
                        else
                        {
                            <option value="@publisher.Id">@publisher.Name.ToString()</option>
                        }

                    }
                </select>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Ispit.Books/Views/BookAdmin/Index.cshtml
@model IEnumerable<Book>



<h1>Administration page</h1>
<hr />

<div class="text-center">
    <h1 class="display-4">Book Collection</h1>
</div>


<a asp-action="Create">Add new book</a>

<hr />

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4">
            <div class="card text-dark bg-light mb-3">
                <div class="card-header">Author: @item.Author.Name </div>
                <div class="card-body">
                    <h5 class="card-title">Title: @item.Title</h5>
                    <hr \>
                    <p class="card-text">Publisher: @item.Publisher.Name</p>
                    <p class="card-text">Genre: @item.Genre</p>
                    <p class="card-text">Description: @item.Description</p>
                    <hr \>
                    <p>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </p>
                </div>

            </div>
        </div>
    }
</div>

Ispit.Books/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Book Collection</h1>
    <p>Login or register your account</p>
</div>

Ispit.Books/Views/Shared/_AdminPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Ispit.Books.Data

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


@if(SignInManager.IsSignedIn(User)) 
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="BookAdmin" asp-action="Index">Administration</a>
    </li>
}

Ispit.Books/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ispit.Books</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ispit.Books.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ispit.Books</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <partial name="_AdminPartial" />
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Ispit.Books - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>